### ISSUE TITLE
Licence window bug

### ISSUE THREAD

**Issue by yardstudio** [nazuke/SEOMacroscope#27]
## SEO Macroscope issues

Please note that it can be very useful to provide the URL of the website or pages that you were attempting to crawl with SEO Macroscope. This will greatly aid the debugging process.

If you would prefer not to post a website URL here, then please provide it via the project's main email address:

> seo.macroscope@gmail.com

To aid debugging, it may be necessary to scan a sample of pages of any given URL.

### Expected behavior:
i can view licence windows

### Actual behavior:
Error dotnet showed 

```
See the end of this message for details on invoking 
just-in-time (JIT) debugging instead of this dialog box.

************** Exception Text **************
System.ArgumentNullException: Value cannot be null.
Parameter name: stream
   at System.IO.StreamReader..ctor(Stream stream, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean leaveOpen)
   at System.IO.StreamReader..ctor(Stream stream)
   at SEOMacroscope.MacroscopeLicenceForm.CallbackLicenceFormShown(Object sender, EventArgs e)
   at System.Windows.Forms.Form.OnShown(EventArgs e)
   at System.Windows.Forms.Control.InvokeMarshaledCallbackHelper(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Windows.Forms.Control.InvokeMarshaledCallback(ThreadMethodEntry tme)
   at System.Windows.Forms.Control.InvokeMarshaledCallbacks()


************** Loaded Assemblies **************
mscorlib
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3163.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
SEOMacroscopeSeriesOne
    Assembly Version: 1.7.4.0
    Win32 Version: 1.7.4.0
    CodeBase: file:///C:/Program%20Files/SEO%20Macroscope/SEOMacroscopeSeriesOne.exe
----------------------------------------
System.Windows.Forms
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3163.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3163.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3163.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
System.Configuration
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0 built by: NET471REL1
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3163.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3163.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
System.Windows.Forms.DataVisualization
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.2558.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.DataVisualization/v4.0_4.0.0.0__31bf3856ad364e35/System.Windows.Forms.DataVisualization.dll
----------------------------------------
System.Data
    Assembly Version: 4.0.0.0
    Win32 Version: 4.7.3163.0 built by: NET472REL1LAST_C
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
----------------------------------------
System.Net.Http.WinHttpHandler
    Assembly Version: 4.0.3.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/Program%20Files/SEO%20Macroscope/System.Net.Http.WinHttpHandler.DLL
----------------------------------------
System.Net.Http
    Assembly Version: 4.2.0.0
    Win32 Version: 4.6.26011.01
    CodeBase: file:///C:/Program%20Files/SEO%20Macroscope/System.Net.Http.DLL
----------------------------------------
RobotsTxt
    Assembly Version: 1.0.5163.29496
    Win32 Version: 1.0.0.0
    CodeBase: file:///C:/Program%20Files/SEO%20Macroscope/RobotsTxt.DLL
----------------------------------------
System.Memory
    Assembly Version: 4.0.1.0
    Win32 Version: 4.6.26606.05
    CodeBase: file:///C:/Program%20Files/SEO%20Macroscope/System.Memory.DLL
----------------------------------------
netstandard
    Assembly Version: 2.0.0.0
    Win32 Version: 4.7.2558.0
    CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/netstandard/v4.0_2.0.0.0__cc7b13ffcd2ddd51/netstandard.dll
----------------------------------------
System.Runtime.CompilerServices.Unsafe
    Assembly Version: 4.0.4.0
    Win32 Version: 
    CodeBase: file:///C:/Program%20Files/SEO%20Macroscope/System.Runtime.CompilerServices.Unsafe.DLL
----------------------------------------
System.Runtime
    Assembly Version: 4.1.2.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files/SEO%20Macroscope/System.Runtime.DLL
----------------------------------------
System.Buffers
    Assembly Version: 4.0.3.0
    Win32 Version: 4.6.26515.06
    CodeBase: file:///C:/Program%20Files/SEO%20Macroscope/System.Buffers.DLL
----------------------------------------
HtmlAgilityPack
    Assembly Version: 1.8.7.0
    Win32 Version: 1.8.7
    CodeBase: file:///C:/Program%20Files/SEO%20Macroscope/HtmlAgilityPack.DLL
----------------------------------------
ExCSS
    Assembly Version: 2.0.6.0
    Win32 Version: 2.0.6
    CodeBase: file:///C:/Program%20Files/SEO%20Macroscope/ExCSS.DLL
----------------------------------------
System.Collections
    Assembly Version: 4.0.11.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files/SEO%20Macroscope/System.Collections.DLL
----------------------------------------
System.Runtime.Extensions
    Assembly Version: 4.1.2.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files/SEO%20Macroscope/System.Runtime.Extensions.DLL
----------------------------------------
System.IO
    Assembly Version: 4.1.2.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files/SEO%20Macroscope/System.IO.DLL
----------------------------------------
System.Globalization
    Assembly Version: 4.0.11.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files/SEO%20Macroscope/System.Globalization.DLL
----------------------------------------
System.Linq
    Assembly Version: 4.1.2.0
    Win32 Version: 4.6.25714.01
    CodeBase: file:///C:/Program%20Files/SEO%20Macroscope/System.Linq.DLL
----------------------------------------
LanguageDetection
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0
    CodeBase: file:///C:/Program%20Files/SEO%20Macroscope/LanguageDetection.DLL
----------------------------------------

************** JIT Debugging **************
To enable just-in-time (JIT) debugging, the .config file for this
application or computer (machine.config) must have the
jitDebugging value set in the system.windows.forms section.
The application must also be compiled with debugging
enabled.

For example:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

When JIT debugging is enabled, any unhandled exception
will be sent to the JIT debugger registered on the computer
rather than be handled by this dialog box.



```

### Steps to reproduce the problem:
Open sw
Click Help/Licence

### Operating System version:
Windows 7PRO 64

![image](https://user-images.githubusercontent.com/25852179/48305103-10034300-e525-11e8-8083-13933a473cb4.png)

**Comment by nazuke** [comment]
This bug should now be fixed.
